# -*- coding: utf-8 -*-
"""tanh.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1au0Kykr_HFL0K9GSAwsPoU7PbB-iH5C3
"""

import numpy as np
import matplotlib.pyplot as plt
import streamlit as st
x = np.linspace(-10, 10, 400)
y = np.tanh(x)

plt.figure()
plt.plot(x, y)
plt.xlabel("Input")
plt.ylabel("Output")
plt.title("Tanh Activation Function")

# Change this line
st.pyplot(plt.gcf())